SCR_MissionHeader {
 World "{15BFE3221A64B55A}gmworld.ent"
 m_sName "<Insert world name>"
 m_sAuthor "<Insert your name>"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}