SCR_MissionHeader {
 World "{BF48CC0566BB49D0}Tarkov.ent"
 m_sName "TestGm"
 m_sAuthor "Huy"
 m_sDescription "-"
 m_sDetails "-"
 m_sGameMode "GameMaster"
 m_iPlayerCount 9
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
}